### ISSUE TITLE
Implement iOS SDK

### ISSUE THREAD

**Issue by nprail** [eventOneHQ/capacitor-stripe-terminal#1]
### To-Do
- [ ] Implement Terminal iOS SDK
  - [x] Fetch connection tokens
  - [x] Discover readers
  - [x] Connect/disconnect a reader
  - [x] Check for & install reader firmware updates
  - [ ] Create payment intents (see #44)
  - [x] Retrieve payment intents
  - [x] Collect payment methods
  - [x] Process payments
- [ ] Usage docs

### Resources
- [Stripe Terminal iOS SDK Docs](https://stripe.com/docs/terminal/sdk/ios)
- [Example App](https://github.com/stripe/stripe-terminal-ios/tree/master/Example)
- [React Native Stripe Terminal Bridge](https://github.com/theopolisme/react-native-stripe-terminal)
