### ISSUE TITLE
Implement Android SDK

### ISSUE THREAD

**Issue by nprail** [eventOneHQ/capacitor-stripe-terminal#3]
### To-Do
- [ ] Implement Terminal Android SDK

  - [x] Fetch connection tokens
  - [x] Discover readers
  - [x] Connect/disconnect a reader
  - [x] Check for & install reader firmware updates
  - [ ] Create payment intents (see #44)
  - [x] Retrieve payment intents
  - [x] Collect payment methods
  - [x] Process payments
- [ ] Usage docs

### Resources
- [Stripe Terminal Android SDK Docs](https://stripe.com/docs/terminal/sdk/android)
- [Example App](https://github.com/stripe/stripe-terminal-android/tree/master/Example)
- [React Native Stripe Terminal Bridge](https://github.com/theopolisme/react-native-stripe-terminal)

**Comment by kyleabens** [comment]
Hey @nprail any update on this?

**Comment by nprail** [comment]
@kyleabens No updates at the moment. My primary focus is on iOS right now because eventOne's use-case requires it the most. But Android will likely increase in priority in the next few months. 

I'm definitely open to a PR.

**Comment by djeter** [comment]
very excited that this is moving forward!!!
