### ISSUE TITLE
Implement JS SDK

### ISSUE THREAD

**Issue by nprail** [eventOneHQ/capacitor-stripe-terminal#4]
Stripe Terminal has a JavaScript SDK for its Verifone countertop card readers. Since Capacitor focuses on both native and PWA platforms, should `capacitor-stripe-terminal` wrap the JS SDK as well? 

At eventOne, we don't need the JS SDK since we only use the BBPOS readers. However, supporting the JS SDK would be a great feature for users who use both types of readers. Having a single JS API between platforms and devices would be awesome (and is something that you can't even do with Stripe's existing SDKs). 

I will definitely accept any PRs for adding this feature. 

### To-Do
- [ ] Implement Terminal JS SDK

  - [x] Fetch connection tokens
  - [x] Discover readers
  - [x] Connect/disconnect a reader
  - [ ] ~Check for & install reader firmware updates~
  - [ ] ~Create payment intents~ (see #44)
  - [x] Retrieve payment intents
  - [x] Collect payment methods
  - [x] Process payments

**Comment by kyleabens** [comment]
Im starting to dive into Stripe terminal now and 100% agree that supporting both SDK's with this one plugin would be a game changer.

**Comment by nprail** [comment]
@kyleabens Agreed. I'll probably implement it at some point. It probably won't even take to long (being a simple wrapper). It's just a matter of when I have time.

Out of curiosity, what's your use-case for Stripe Terminal?

**Comment by nprail** [comment]
@kyleabens Basic support for the JS SDK has been added. See the [known limitations](https://github.com/eventOneHQ/capacitor-stripe-terminal/issues/6)  for what it doesn't support yet.

**Comment by kyleabens** [comment]
@nprail I've finally got around to updating the plugin and I'm experiencing an issue on Android when I attempt to discover readers now.  `"Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference"`.  Any idea what this could be referring to?

**Comment by kyleabens** [comment]
Also when I switch deviceType to DeviceType.VerifoneP400 I get this error.

<img width="899" alt="Screen Shot 2020-11-20 at 2 14 11 PM" src="https://user-images.githubusercontent.com/25699262/99840591-d1081f00-2b3a-11eb-8e6b-7409df81c5e9.png">

**Comment by nprail** [comment]
@kyleabens Could you create two separate new issues for those? I'm guessing they are unrelated to each other (and unrelated to the JS SDK). 

Thanks!

**Comment by kyleabens** [comment]
@nprail Okay and is there no way to scan for both Verifone P400 and BBPOS Chipper 2X BT readers at the same time?  Do I always have to specify a deviceType? My app is a PWA so I should be allowed to connect to not only the Bluetooth reader but also the Verifone P400 via the internet.

**Comment by nprail** [comment]
@kyleabens No, unfortunately, Stripe's SDKs do not provide any way of doing that.
